name: Radio Recorder

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg python3-pip
          pip install google-api-python-client google-auth

      - name: Record stream
        run: |
          ffmpeg -y \
          -i http://icecast.di.unipmn.it:8000/6023hq \
          -t 9000 \
          -c copy radio-$(date +%F).mp3

      - name: Upload to Drive
        env:
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}
        run: |
          echo "$GDRIVE_KEY" > key.json

          python3 <<EOF
          from google.oauth2 import service_account
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload
          import os

          SCOPES=['https://www.googleapis.com/auth/drive']

          creds=service_account.Credentials.from_service_account_file(
          'key.json',scopes=SCOPES)

          service=build('drive','v3',credentials=creds)

          folder_name="RegistrazioniRadio"

          query=f"name='{folder_name}' and mimeType='application/vnd.google-apps.folder'"

          folder=service.files().list(q=query,fields="files(id)").execute()

          folder_id=folder['files'][0]['id']

          file=[f for f in os.listdir('.') if f.endswith('.mp3')][0]

          media=MediaFileUpload(file,resumable=True)

          service.files().create(
          body={'name':file,'parents':[folder_id]},
          media_body=media).execute()

          print("UPLOAD OK")
          EOF
